# Generated by Django 6.0.2 on 2026-02-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_product_pic_alter_order_customer_alter_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, upload_to='product_image/'),
        ),
    ]
